In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
car = pd.read_excel("../../data/interim/transformed_car.xlsx")
car.head()

,name,year,selling_price,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,Maruti 800 AC,2007,60000,70000,1,0,0,0,0,1,0,1,0,0,1
1,Maruti Wagon R LXI Minor,2007,135000,50000,1,0,0,0,0,1,0,1,0,0,1
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,0,1,0,0,0,0,1,0,0,1
3,Datsun RediGO T Option,2017,250000,46000,1,0,0,0,0,1,0,1,0,0,1
4,Honda Amaze VX i-DTEC,2014,450000,141000,2,0,1,0,0,0,0,1,0,0,1

In [3]:
print(car.shape)
print(car.isna().sum())
print(car.duplicated().sum())

(3560, 15)
name                            0
year                            0
selling_price                   0
km_driven                       0
owner                           0
fuel_CNG                        0
fuel_Diesel                     0
fuel_Electric                   0
fuel_LPG                        0
fuel_Petrol                     0
seller_type_Dealer              0
seller_type_Individual          0
seller_type_Trustmark Dealer    0
transmission_Automatic          0
transmission_Manual             0
dtype: int64
0

In [7]:
x = car.drop(columns=["selling_price","name"])
x.head()

,year,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,2007,70000,1,0,0,0,0,1,0,1,0,0,1
1,2007,50000,1,0,0,0,0,1,0,1,0,0,1
2,2012,100000,1,0,1,0,0,0,0,1,0,0,1
3,2017,46000,1,0,0,0,0,1,0,1,0,0,1
4,2014,141000,2,0,1,0,0,0,0,1,0,0,1

In [9]:
y = car["selling_price"]
y.head()

0     60000
1    135000
2    600000
3    250000
4    450000
Name: selling_price, dtype: int64

In [22]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size= 0.2,
    random_state= True
)
x_train.head()

,year,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
1917,2014,110000,2,0,1,0,0,0,0,1,0,0,1
1783,2010,90000,2,0,0,0,0,1,0,1,0,0,1
1732,2012,120000,1,0,1,0,0,0,0,1,0,0,1
1892,2017,80000,1,0,1,0,0,0,0,1,0,0,1
846,2020,1500,1,0,1,0,0,0,0,1,0,1,0

In [23]:
print("X_train:", x_train.shape)
print("X_test:", x_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (2848, 13)
X_test: (712, 13)
y_train: (2848,)
y_test: (712,)

In [25]:
x_train.to_excel("../../data/processed/x_train.xlsx",index=False)

In [28]:
x_test.to_excel("../../data/processed/x_test.xlsx", index=False)
y_train.to_excel("../../data/processed/y_train.xlsx",index=False)
y_test.to_excel("../../data/processed/y_test.xlsx",index=False)