In [1]:
import pandas as pd
import joblib
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score
)

In [2]:
x_test = pd.read_excel("../../data/processed/x_test.xlsx")
x_train = pd.read_excel("../../data/processed/x_train.xlsx")
y_train = pd.read_excel("../../data/processed/y_train.xlsx")
y_test = pd.read_excel("../../data/processed/y_test.xlsx")
print(x_test.shape)
x_test.head()

(712, 13)

,year,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,2017,120000,1,0,1,0,0,0,0,1,0,0,1
1,2019,35000,1,0,1,0,0,0,0,1,0,0,1
2,2012,80000,1,0,1,0,0,0,0,1,0,0,1
3,2019,60000,1,0,1,0,0,0,0,1,0,0,1
4,2014,101000,2,0,1,0,0,0,0,1,0,0,1

In [3]:
# load the model -- linear regression
model = joblib.load("../../models/linear_regression.pkl")

# predict 
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

# metrics
train_mae = mean_absolute_error(y_train,y_train_pred)
test_mae = mean_absolute_error(y_test,y_test_pred)

train_mse = mean_squared_error(y_train,y_train_pred)
test_mse = mean_squared_error(y_test,y_test_pred)

train_rmse = root_mean_squared_error(y_train,y_train_pred)
test_rmse = root_mean_squared_error(y_test,y_test_pred)

train_r2 = r2_score(y_train,y_train_pred)
test_r2 = r2_score(y_test,y_test_pred)

print("Train MAE:", train_mae)
print("Test MAE:", test_mae,"\n")

print("Train MSE:",train_mse)
print("Test MSE:", test_mse,"\n")

print("Train RMSE:",train_rmse)
print("Test RMSE:", test_rmse,"\n")

print("Train R2_Score:", train_r2)
print("Test R2_Score:", test_r2)

Train MAE: 203231.4431378067
Test MAE: 211996.4083268254

Train MSE: 132411304626.22638
Test MSE: 205227673439.7305

Train RMSE: 363883.641602953
Test RMSE: 453020.6103917685

Train R2_Score: 0.45560900645391467
Test R2_Score: 0.3640598880125786

In [4]:
# polynomial regression
results = []
for degree in range(2,5):
    # load the features
    poly = joblib.load(f"../../models/polynomial_features_degree{degree}.pkl")

    #load the model
    poly_model = joblib.load(f"../../models/polynomial_regression_degree{degree}.pkl")

    # transoforme test data
    x_train_poly = poly.transform(x_train)
    x_test_poly = poly.transform(x_test)

    # predict
    y_train_pred = poly_model.predict(x_train_poly)
    y_test_pred = poly_model.predict(x_test_poly)

    # metrics
    train_mae_poly = mean_absolute_error(y_train,y_train_pred)
    test_mae_poly = mean_absolute_error(y_test,y_test_pred)

    train_mse_poly = mean_squared_error(y_train,y_train_pred)
    test_mse_poly = mean_squared_error(y_test,y_test_pred)

    train_rmse_poly = root_mean_squared_error(y_train,y_train_pred)
    test_rmse_poly = root_mean_squared_error(y_test,y_test_pred)

    train_r2_poly = r2_score(y_train,y_train_pred)
    test_r2_poly = r2_score(y_test,y_test_pred)

    results.append(
        {
            "degree": degree,
            "Train MAE": train_mae_poly,
            "Test MAE" : test_mae_poly,
            "Train MSE": train_mse_poly,
            "Test MSE": test_mse_poly,
            "Train RMSE": train_rmse_poly,
            "Test RMSE": test_rmse_poly,
            "Train R2": train_r2_poly,
            "Test R2": test_r2_poly
        }
    )
pd.DataFrame(results)

,degree,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,2,181277.330189,195304.167968,1.103156e+11,1.947649e+11,332137.976272,441321.799145,0.546452,0.396481
1,3,187615.796693,201995.313497,1.178097e+11,1.996276e+11,343234.186125,446797.017555,0.515641,0.381413
2,4,206579.543006,214353.960999,1.427623e+11,2.182703e+11,377838.994623,467194.054255,0.413052,0.323645

In [5]:
# Ridge regression
scaler = joblib.load("../../models/scaler.pkl")

results = []

for alpha in [0.01,0.1,1.0,10,100]:
    # load the model
    ridge_model = joblib.load(f"../../models/ridge_regression{alpha}.pkl")

    x_train_scaled = scaler.transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # predict
    y_train_pred_ridge = ridge_model.predict(x_train_scaled)
    y_test_pred_ridge = ridge_model.predict(x_test_scaled)

    # metrics
    train_mae_ridge = mean_absolute_error(y_train,y_train_pred_ridge)
    test_mae_ridge = mean_absolute_error(y_test,y_test_pred_ridge)

    train_mse_ridge = mean_squared_error(y_train,y_train_pred_ridge)
    test_mse_ridge = mean_squared_error(y_test,y_test_pred_ridge)

    train_rmse_ridge = root_mean_squared_error(y_train,y_train_pred_ridge)
    test_rmse_ridge = root_mean_squared_error(y_test,y_test_pred_ridge)

    train_r2_ridge = r2_score(y_train,y_train_pred_ridge)
    test_r2_ridge = r2_score(y_test,y_test_pred_ridge)

    results.append(
        {
            "Alpha":alpha,
            "Train MAE": train_mae_ridge,
            "Test MAE": test_mae_ridge,
            "Train MSE": train_mse_ridge,
            "Test MSE": test_mse_ridge,
            "Train RMSE": train_rmse_ridge,
            "Test RMSE": test_rmse_ridge,
            "Train R2": train_r2_ridge,
            "Test R2": test_r2_ridge
        }
    )
pd.DataFrame(results)

,Alpha,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,0.01,203231.316289,211996.297591,1.324113e+11,2.052277e+11,363883.641604,453020.626896,0.455609,0.364060
1,0.10,203230.174675,211995.300988,1.324113e+11,2.052278e+11,363883.641662,453020.775477,0.455609,0.364059
2,1.00,203218.761495,211985.337306,1.324113e+11,2.052292e+11,363883.647492,453022.265358,0.455609,0.364055
3,10.00,203105.190959,211885.933894,1.324117e+11,2.052430e+11,363884.226953,453037.568529,0.455607,0.364012
4,100.00,202048.449922,210936.970339,1.324515e+11,2.054159e+11,363938.833533,453228.270952,0.455444,0.363477

In [6]:
# lasso regression
scaler = joblib.load("../../models/scaler.pkl")

results = []

for alpha in [1,10,100,1000]:
    # load the model
    lasso_model = joblib.load(f"../../models/lasso_regression{alpha}.pkl")

    #scale the train & test data
    x_train_scaled = scaler.transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    #predict
    y_train_pred_lasso = lasso_model.predict(x_train_scaled)
    y_test_pred_lasso = lasso_model.predict(x_test_scaled)

    # metrics
    train_mae_lasso = mean_absolute_error(y_train,y_train_pred_lasso)
    test_mae_lasso = mean_absolute_error(y_test,y_test_pred_lasso)

    train_mse_lasso = mean_squared_error(y_train,y_train_pred_lasso)
    test_mse_lasso = mean_squared_error(y_test, y_test_pred_lasso)

    train_rmse_lasso = root_mean_squared_error(y_train,y_train_pred_lasso)
    test_rmse_lasso = root_mean_squared_error(y_test,y_test_pred_lasso)

    train_r2_lasso = r2_score(y_train,y_train_pred_lasso)
    test_r2_lasso = r2_score(y_test,y_test_pred_lasso)

    results.append(
        {
            "Alpha":alpha,
            "Train MAE": train_mae_lasso,
            "Test MAE": test_mae_lasso,
            "Train MSE": train_mse_lasso,
            "Test MSE": test_mse_lasso,
            "Train RMSE": train_rmse_lasso,
            "Test RMSE": test_rmse_lasso,
            "Train R2": train_r2_lasso,
            "Test R2": test_r2_lasso
        }
    )
pd.DataFrame(results)

,Alpha,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,1,203231.048173,211996.083237,1.324113e+11,2.052278e+11,363883.641614,453020.711315,0.455609,0.364060
1,10,203227.496308,211993.159276,1.324113e+11,2.052286e+11,363883.642699,453021.619996,0.455609,0.364057
2,100,203192.023324,211963.849940,1.324114e+11,2.052369e+11,363883.750916,453030.765002,0.455609,0.364031
3,1000,202860.269937,211667.476654,1.324190e+11,2.053238e+11,363894.180457,453126.642864,0.455577,0.363762

In [10]:
# ElasticNet regression
scaler = joblib.load("../../models/scaler.pkl")

results = []

for alpha in [1,10,100,1000]:
    # load the model 
    elasticnet_model = joblib.load(f"../../models/elasticNet_regression_{alpha}.pkl")

    # scaled the train & test data
    x_train_scaled = scaler.transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # predict
    y_train_pred_elastic = elasticnet_model.predict(x_train_scaled)
    y_test_pred_elastic = elasticnet_model.predict(x_test_scaled)

    # metrics
    train_mae_EN = mean_absolute_error(y_train,y_train_pred_elastic)
    test_mae_EN = mean_absolute_error(y_test,y_test_pred_elastic)

    train_mse_EN = mean_squared_error(y_train,y_train_pred_elastic)
    test_mse_EN = mean_squared_error(y_test,y_test_pred_elastic)

    train_rmse_EN = root_mean_squared_error(y_train,y_train_pred_elastic)
    test_rmse_EN = root_mean_squared_error(y_test,y_test_pred_elastic)

    train_r2_EN = r2_score(y_train,y_train_pred_elastic)
    test_r2_EN = r2_score(y_test,y_test_pred_elastic)

    results.append(
        {
            "Alpha":alpha,
            "Train MAE": train_mae_EN,
            "Test MAE": test_mae_EN,
            "Train MSE": train_mse_EN,
            "Test MSE": test_mse_EN,
            "Train RMSE": train_rmse_EN,
            "Test RMSE": test_rmse_EN,
            "Train R2": train_r2_EN,
            "Test R2": test_r2_EN
        }
    )
pd.DataFrame(results)

,Alpha,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,1,197590.470673,207124.269944,1.369373e+11,2.115168e+11,370050.463908,459909.542823,0.437001,0.344572
1,10,241520.365146,256309.780337,1.864041e+11,2.649565e+11,431745.366913,514739.263756,0.233625,0.178978
2,100,281877.657265,294521.843327,2.340173e+11,3.136602e+11,483753.346528,560053.746967,0.037870,0.028059
3,1000,288425.665479,300805.354128,2.422516e+11,3.219768e+11,492190.612077,567429.986390,0.004016,0.002289

In [27]:
# Decision Tree regression

#load the model 
decision_model = joblib.load("../../models/decision_tree_regressor.pkl")

# predict
y_train_pred_decision = decision_model.predict(x_train)
y_test_pred_decision = decision_model.predict(x_test)

# metrics
train_mae_decision = mean_absolute_error(y_train,y_train_pred_decision)
test_mae_decision = mean_absolute_error(y_test,y_test_pred_decision) 

train_mse_decision = mean_squared_error(y_train,y_train_pred_decision)
test_mse_decision = mean_squared_error(y_test,y_test_pred_decision)

train_rmse_decision = root_mean_squared_error(y_train,y_train_pred_decision)
test_rmse_decision = root_mean_squared_error(y_test,y_test_pred_decision)

train_r2_decision = r2_score(y_train,y_train_pred_decision)
test_r2_decision = r2_score(y_test,y_test_pred_decision)


print("Train MAE:", train_mae_decision)
print("Test MAE:", test_mae_decision,"\n")

print("Train MSE:",train_mse_decision)
print("Test MSE:", test_mse_decision,"\n")

print("Train RMSE:",train_rmse_decision)
print("Test RMSE:", test_rmse_decision,"\n")

print("Train R2_Score:", train_r2_decision)
print("Test R2_Score:", test_r2_decision)

Train MAE: 147618.77131539927
Test MAE: 187943.14836216715

Train MSE: 73038192989.30675
Test MSE: 202143945390.69583

Train RMSE: 270255.79177754314
Test RMSE: 449604.20971193747

Train R2_Score: 0.6997134454607284
Test R2_Score: 0.3736154529516206

In [33]:
# Random forest regression

#load the model
rf_model = joblib.load("../../models/random_forest_regression.pkl")

# predict 
y_train_pred_rf = rf_model.predict(x_train)
y_test_pred_rf = rf_model.predict(x_test)

# metrics
train_mae_rf = mean_absolute_error(y_train,y_train_pred_rf)
test_mae_rf = mean_absolute_error(y_test,y_test_pred_rf) 

train_mse_rf = mean_squared_error(y_train,y_train_pred_rf)
test_mse_rf = mean_squared_error(y_test,y_test_pred_rf)

train_rmse_rf = root_mean_squared_error(y_train,y_train_pred_rf)
test_rmse_rf = root_mean_squared_error(y_test,y_test_pred_rf)

train_r2_rf = r2_score(y_train,y_train_pred_rf)
test_r2_rf = r2_score(y_test,y_test_pred_rf)


print("Train MAE:", train_mae_rf)
print("Test MAE:", test_mae_rf,"\n")

print("Train MSE:",train_mse_rf)
print("Test MSE:", test_mse_rf,"\n")

print("Train RMSE:",train_rmse_rf)
print("Test RMSE:", test_rmse_rf,"\n")

print("Train R2_Score:", train_r2_rf)
print("Test R2_Score:", test_r2_rf)

Train MAE: 133781.89008007073
Test MAE: 182839.52423909615

Train MSE: 59709916020.56825
Test MSE: 193749868208.76974

Train RMSE: 244356.12540013858
Test RMSE: 440170.27183667204

Train R2_Score: 0.7545108357723094
Test R2_Score: 0.39962622573696227

In [32]:
# gradientBoostingRegressor

#load the model 
gradient_model = joblib.load("../../models/gradientBoosting.pkl")

# predict
y_train_pred_gradient = gradient_model.predict(x_train)
y_test_pred_gradient = gradient_model.predict(x_test)

# metrics
train_mae_gradient = mean_absolute_error(y_train,y_train_pred_gradient)
test_mae_gradient = mean_absolute_error(y_test,y_test_pred_gradient) 

train_mse_gradient = mean_squared_error(y_train,y_train_pred_gradient)
test_mse_gradient = mean_squared_error(y_test,y_test_pred_gradient)

train_rmse_gradient = root_mean_squared_error(y_train,y_train_pred_gradient)
test_rmse_gradient = root_mean_squared_error(y_test,y_test_pred_gradient)

train_r2_gradient = r2_score(y_train,y_train_pred_gradient)
test_r2_gradient = r2_score(y_test,y_test_pred_gradient)


print("Train MAE:", train_mae_gradient)
print("Test MAE:", test_mae_gradient,"\n")

print("Train MSE:",train_mse_gradient)
print("Test MSE:", test_mse_gradient,"\n")

print("Train RMSE:",train_rmse_gradient)
print("Test RMSE:", test_rmse_gradient,"\n")

print("Train R2_Score:", train_r2_gradient)
print("Test R2_Score:", test_r2_gradient)

Train MAE: 85108.77048199781
Test MAE: 199083.2620106512

Train MSE: 19066221317.205612
Test MSE: 225478016204.30896

Train RMSE: 138080.48854637504
Test RMSE: 474845.2550087333

Train R2_Score: 0.9216118352179782
Test R2_Score: 0.30131004034512165

In [44]:
# XGBoost Regression

# load the model 
xgb_model = joblib.load("../../models/xgboost_regression.pkl")

# predict
y_train_pred_xgb = xgb_model.predict(x_train)
y_test_pred_xgb = xgb_model.predict(x_test)


# metrics
train_mae_xgb = mean_absolute_error(y_train,y_train_pred_xgb)
test_mae_xgb = mean_absolute_error(y_test,y_test_pred_xgb) 

train_mse_xgb = mean_squared_error(y_train,y_train_pred_xgb)
test_mse_xgb = mean_squared_error(y_test,y_test_pred_xgb)

train_rmse_xgb = root_mean_squared_error(y_train,y_train_pred_xgb)
test_rmse_xgb = root_mean_squared_error(y_test,y_test_pred_xgb)

train_r2_xgb = r2_score(y_train,y_train_pred_xgb)
test_r2_xgb = r2_score(y_test,y_test_pred_xgb)


print("Train MAE:", train_mae_xgb)
print("Test MAE:", test_mae_xgb,"\n")

print("Train MSE:",train_mse_xgb)
print("Test MSE:", test_mse_xgb,"\n")

print("Train RMSE:",train_rmse_xgb)
print("Test RMSE:", test_rmse_xgb,"\n")

print("Train R2_Score:", train_r2_xgb)
print("Test R2_Score:", test_r2_xgb)

Train MAE: 157228.140625
Test MAE: 184215.703125

Train MSE: 78075297792.0
Test MSE: 202449682432.0

Train RMSE: 279419.5625
Test RMSE: 449944.09375

Train R2_Score: 0.6790040731430054
Test R2_Score: 0.3726680874824524