In [59]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import (Ridge,Lasso,ElasticNet)
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import joblib

In [9]:
x_train = pd.read_excel("../../data/processed/x_train.xlsx")
x_test = pd.read_excel("../../data/processed/x_test.xlsx")
y_train = pd.read_excel("../../data/processed/y_train.xlsx")
x_train.head()

,year,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,2014,110000,2,0,1,0,0,0,0,1,0,0,1
1,2010,90000,2,0,0,0,0,1,0,1,0,0,1
2,2012,120000,1,0,1,0,0,0,0,1,0,0,1
3,2017,80000,1,0,1,0,0,0,0,1,0,0,1
4,2020,1500,1,0,1,0,0,0,0,1,0,1,0

In [4]:
y_train.head()

   selling_price
0         315000
1         150000
2         165000
3         575000
4        4700000

In [38]:
# future scaling 
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [25]:
# linear regression model training
model = LinearRegression()
model.fit(x_train_scaled, y_train)

for features, coeffiecents in zip(x_train.columns,model.coef_[0]):
    print(features, ":", coeffiecents)
print("intercept:",model.intercept_)
joblib.dump(model, "../../models/linear_regression.pkl")

year : 142745.36378125995
km_driven : -41350.93620890947
owner : -19004.748077889275
fuel_CNG : -14065.41616170698
fuel_Diesel : 68032.22231675679
fuel_Electric : -12268.217209985363
fuel_LPG : -6997.406021460324
fuel_Petrol : -63578.534580315085
seller_type_Dealer : 10153.268225115135
seller_type_Individual : -11712.147112039442
seller_type_Trustmark Dealer : 7241.52147629895
transmission_Automatic : 108133.99222707367
transmission_Manual : -108133.99222707366
intercept: [468479.46067416]

['../../models/linear_regression.pkl']

In [37]:
# polynomial regression
for degree in range(2,5):
        
    poly = PolynomialFeatures(degree=degree)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.transform(x_test)

    poly_model = LinearRegression()
    poly_model.fit(x_train_poly,y_train)

    joblib.dump(poly, f"../../models/polynomial_features_degree{degree}.pkl")

    joblib.dump(poly_model, f"../../models/polynomial_regression_degree{degree}.pkl")

In [42]:
# Ridge regression
for alpha in [0.01,0.1,1.0,10,100]:
    ridge_model = Ridge(alpha=alpha)
    ridge_model.fit(x_train_scaled,y_train)
    joblib.dump(ridge_model, f"../../models/ridge_regression{alpha}.pkl")

In [51]:
# lasso regression
for alpha in [1,10,100,1000]:
    lasso_model = Lasso(alpha=alpha,max_iter=100000)
    lasso_model.fit(x_train_scaled,y_train)
    joblib.dump(lasso_model, f"../../models/lasso_regression{alpha}.pkl")

In [56]:
# ElasticNet regression
for alpha in [1,10,100,1000]:

    elasticNet_model = ElasticNet(alpha=alpha, l1_ratio=0.5, max_iter=10000)
    elasticNet_model.fit(x_train_scaled,y_train)
    joblib.dump(elasticNet_model, f"../../models/elasticNet_regression_{alpha}.pkl")

In [ ]:
# Decision Tree Regressor
decision_model = DecisionTreeRegressor(
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf= 10,
    random_state=True
)
decision_model.fit(x_train,y_train)
joblib.dump(decision_model, "../../models/decision_tree_regressor.pkl")

['../../models/decision_tree_regressor.pkl']

In [62]:
# Random Forest Regression
rf_model = RandomForestRegressor(
    max_depth= 10,
    min_samples_split=10,
    min_samples_leaf=10,
    n_estimators= 70,
    random_state= 42
)
rf_model.fit(x_train,y_train)
joblib.dump(rf_model,"../../models/random_forest_regression.pkl")

c:\Users\veere\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

['../../models/random_forest_regression.pkl']