In [1]:
import pandas as pd
import joblib
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score
)

In [4]:
x_test = pd.read_excel("../../data/processed/x_test.xlsx")
x_train = pd.read_excel("../../data/processed/x_train.xlsx")
y_train = pd.read_excel("../../data/processed/y_train.xlsx")
y_test = pd.read_excel("../../data/processed/y_test.xlsx")
print(x_test.shape)
x_test.head()

(712, 13)

,year,km_driven,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,2017,120000,1,0,1,0,0,0,0,1,0,0,1
1,2019,35000,1,0,1,0,0,0,0,1,0,0,1
2,2012,80000,1,0,1,0,0,0,0,1,0,0,1
3,2019,60000,1,0,1,0,0,0,0,1,0,0,1
4,2014,101000,2,0,1,0,0,0,0,1,0,0,1

In [ ]:
# load the model -- linear regression
model = joblib.load("../../models/linear_regression.pkl")

# predict 
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

# metrics
train_mae = mean_absolute_error(y_train,y_train_pred)
test_mae = mean_absolute_error(y_test,y_test_pred)

train_mse = mean_squared_error(y_train,y_train_pred)
test_mse = mean_squared_error(y_test,y_test_pred)

train_rmse = root_mean_squared_error(y_train,y_train_pred)
test_rmse = root_mean_squared_error(y_test,y_test_pred)

train_r2 = r2_score(y_train,y_train_pred)
test_r2 = r2_score(y_test,y_test_pred)

print("Train MAE:", train_mae)
print("Test MAE:", test_mae,"\n")

print("Train MSE:",train_mse)
print("Test MSE:", test_mse,"\n")

print("Train RMSE:",train_rmse)
print("Test RMSE:", test_rmse,"\n")

print("Train R2_Score:", train_r2)
print("Test R2_Score:", test_r2)

Train MAE: 203231.4431378067
Test MAE: 211996.4083268254

Train MSE: 132411304626.22638
Test MSE: 205227673439.7305

Train RMSE: 363883.641602953
Test RMSE: 453020.6103917685

Train R2_Score: 0.45560900645391467
Test R2_Score: 0.3640598880125786

In [ ]:
# polynomial regression
results = []
for degree in range(2,5):
    # load the features
    poly = joblib.load(f"../../models/polynomial_features_degree{degree}.pkl")

    #load the model
    poly_model = joblib.load(f"../../models/polynomial_regression_degree{degree}.pkl")

    # transoforme test data
    x_train_poly = poly.transform(x_train)
    x_test_poly = poly.transform(x_test)

    # predict
    y_train_pred = poly_model.predict(x_train_poly)
    y_test_pred = poly_model.predict(x_test_poly)

    # metrics
    train_mae_poly = mean_absolute_error(y_train,y_train_pred)
    test_mae_poly = mean_absolute_error(y_test,y_test_pred)

    train_mse_poly = mean_squared_error(y_train,y_train_pred)
    test_mse_poly = mean_squared_error(y_test,y_test_pred)

    train_rmse_poly = root_mean_squared_error(y_train,y_train_pred)
    test_rmse_poly = root_mean_squared_error(y_test,y_test_pred)

    train_r2_poly = r2_score(y_train,y_train_pred)
    test_r2_poly = r2_score(y_test,y_test_pred)

    results.append(
        {
            "degree": degree,
            "Train MAE": train_mae_poly,
            "Test MAE" : test_mae_poly,
            "Train MSE": train_mse_poly,
            "Test MSE": test_mse_poly,
            "Train RMSE": train_rmse_poly,
            "Test RMSE": test_rmse_poly,
            "Train R2": train_r2_poly,
            "Test R2": test_r2_poly
        }
    )
pd.DataFrame(results)

,degree,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,2,181277.330189,195304.167968,1.103156e+11,1.947649e+11,332137.976272,441321.799145,0.546452,0.396481
1,3,187615.796693,201995.313497,1.178097e+11,1.996276e+11,343234.186125,446797.017555,0.515641,0.381413
2,4,206579.543006,214353.960999,1.427623e+11,2.182703e+11,377838.994623,467194.054255,0.413052,0.323645

In [ ]:
# Ridge regression
scaler = joblib.load("../../models/scaler.pkl")

results = []

for alpha in [0.01,0.1,1.0,10,100]:
    # load the model
    ridge_model = joblib.load(f"../../models/ridge_regression{alpha}.pkl")

    x_train_scaled = scaler.transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # predict
    y_train_pred_ridge = ridge_model.predict(x_train_scaled)
    y_test_pred_ridge = ridge_model.predict(x_test_scaled)

    # metrics
    train_mae_ridge = mean_absolute_error(y_train,y_train_pred_ridge)
    test_mae_ridge = mean_absolute_error(y_test,y_test_pred_ridge)

    train_mse_ridge = mean_squared_error(y_train,y_train_pred_ridge)
    test_mse_ridge = mean_squared_error(y_test,y_test_pred_ridge)

    train_rmse_ridge = root_mean_squared_error(y_train,y_train_pred_ridge)
    test_rmse_ridge = root_mean_squared_error(y_test,y_test_pred_ridge)

    train_r2_ridge = r2_score(y_train,y_train_pred_ridge)
    test_r2_ridge = r2_score(y_test,y_test_pred_ridge)

    results.append(
        {
            "Alpha":alpha,
            "Train MAE": train_mae_ridge,
            "Test MAE": test_mae_ridge,
            "Train MSE": train_mse_ridge,
            "Test MSE": test_mse_ridge,
            "Train RMSE": train_rmse_ridge,
            "Test RMSE": test_rmse_ridge,
            "Train R2": train_r2_ridge,
            "Test R2": test_r2_ridge
        }
    )
pd.DataFrame(results)

,Alpha,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,0.01,203231.316289,211996.297591,1.324113e+11,2.052277e+11,363883.641604,453020.626896,0.455609,0.364060
1,0.10,203230.174675,211995.300988,1.324113e+11,2.052278e+11,363883.641662,453020.775477,0.455609,0.364059
2,1.00,203218.761495,211985.337306,1.324113e+11,2.052292e+11,363883.647492,453022.265358,0.455609,0.364055
3,10.00,203105.190959,211885.933894,1.324117e+11,2.052430e+11,363884.226953,453037.568529,0.455607,0.364012
4,100.00,202048.449922,210936.970339,1.324515e+11,2.054159e+11,363938.833533,453228.270952,0.455444,0.363477

In [ ]:
# lasso regression
scaler = joblib.load("../../models/scaler.pkl")

results = []

for alpha in [1,10,100,1000]:
    # load the model
    lasso_model = joblib.load(f"../../models/lasso_regression{alpha}.pkl")

    #scale the train & test data
    x_train_scaled = scaler.transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    #predict
    y_train_pred_lasso = lasso_model.predict(x_train_scaled)
    y_test_pred_lasso = lasso_model.predict(x_test_scaled)

    # metrics
    train_mae_lasso = mean_absolute_error(y_train,y_train_pred_lasso)
    test_mae_lasso = mean_absolute_error(y_test,y_test_pred_lasso)

    train_mse_lasso = mean_squared_error(y_train,y_train_pred_lasso)
    test_mse_lasso = mean_squared_error(y_test, y_test_pred_lasso)

    train_rmse_lasso = root_mean_squared_error(y_train,y_train_pred_lasso)
    test_rmse_lasso = root_mean_squared_error(y_test,y_test_pred_lasso)

    train_r2_lasso = r2_score(y_train,y_train_pred_lasso)
    test_r2_lasso = r2_score(y_test,y_test_pred_lasso)

    results.append(
        {
            "Alpha":alpha,
            "Train MAE": train_mae_lasso,
            "Test MAE": test_mae_lasso,
            "Train MSE": train_mse_lasso,
            "Test MSE": test_mse_lasso,
            "Train RMSE": train_rmse_lasso,
            "Test RMSE": test_rmse_lasso,
            "Train R2": train_r2_lasso,
            "Test R2": test_r2_lasso
        }
    )
pd.DataFrame(results)

,Alpha,Train MAE,Test MAE,Train MSE,Test MSE,Train RMSE,Test RMSE,Train R2,Test R2
0,1,203231.048173,211996.083237,1.324113e+11,2.052278e+11,363883.641614,453020.711315,0.455609,0.364060
1,10,203227.496308,211993.159276,1.324113e+11,2.052286e+11,363883.642699,453021.619996,0.455609,0.364057
2,100,203192.023324,211963.849940,1.324114e+11,2.052369e+11,363883.750916,453030.765002,0.455609,0.364031
3,1000,202860.269937,211667.476654,1.324190e+11,2.053238e+11,363894.180457,453126.642864,0.455577,0.363762

: